Repository Royal-Society-of-New-Zealand/NZ-ORCID-Hub, pull requests merged in 2019-04, with the labels that each got.

#663 Orcidhub 439
  .gitignore
  orcid_hub/authcontroller.py
  orcid_hub/forms.py
  orcid_hub/models.py
  orcid_hub/orcid_client.py
  orcid_hub/schemas.py
  orcid_hub/static/css/style.css
  orcid_hub/templates/funding_contributor_list.html
  orcid_hub/templates/funding_invitees_list.html
  orcid_hub/templates/funding_record_list.html
  orcid_hub/templates/index.html
  orcid_hub/templates/invitee_list.html
  orcid_hub/templates/peer_review_externalid_invitees_list.html
  orcid_hub/templates/peer_review_record_list.html
  orcid_hub/templates/profile_entry.html
  orcid_hub/templates/record_child_list.html
  orcid_hub/templates/work_contributor_list.html
  orcid_hub/templates/work_externalid_list.html
  orcid_hub/templates/work_invitee_list.html
  orcid_hub/templates/work_invitees_list.html
  orcid_hub/templates/work_record_list.html
  orcid_hub/utils.py
  orcid_hub/views.py
  tests/test_models.py
  tests/test_utils.py
  tests/test_views.py
Labels: db changes, enhancement, refactoring

#666 Orcidhub 437/438
  .travis.yml
  orcid_hub/forms.py
  orcid_hub/models.py
  orcid_hub/orcid_client.py
  orcid_hub/utils.py
  orcid_hub/views.py
  tests/test_utils.py
  tests/test_views.py
Labels: db changes, enhancement

#672 adjusted schema
  orcid_hub/apis.py
  orcid_hub/models.py
  orcid_hub/schemas.py
  tests/data/othernames.csv
  tests/data/othernames.json
  tests/data/researchurls.json
  tests/test_models.py
  tests/test_views.py
Labels: db changes
